### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by cristoslc** [brian-schick/FileMakerSqlSugar#2]
Is this project still active? I see that some of the help documentation is incomplete, such as @.execute.  Are you still using this methodology, or have you found something more effective in the past 2 years?

**Comment by brian-schick** [comment]
Yes, it's still maintained and actively in use. Happy to answer any questions you have. @.execute hasn't been implemented (the usual time constraints), so it's best to simply wrap these in either a native ExecuteSQL or proprietary plugin call.

**Comment by cristoslc** [comment]
Great, thanks!
